; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:adafruit_feather_esp32_v2]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = adafruit_feather_esp32_v2
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
build_flags =
    -DCORE_DEBUG_LEVEL=3
lib_deps =
    https://github.com/pschatzmann/ESP32-A2DP.git
    https://github.com/pschatzmann/arduino-audio-tools.git
    adafruit/Adafruit TLV320 I2S
    adafruit/Adafruit NeoPixel
    adafruit/Adafruit BusIO
    knolleary/PubSubClient @ ^2.8
